const Order = require('../../models/Order');
const Merchant = require('../../models/Merchant');

const OrderResolvers = {
  Query: {
    getOrderHistory: async (_, { customerId }) => {
      try {
        const orders = await Order.find({ customerId }).sort({ createdAt: -1 });
        return orders.map(order => ({
          ...order.toObject(),
          id: order._id.toString(),
        }));
      } catch (error) {
        throw new Error("Failed to fetch order history");
      }
    },

    getOrderById: async (_, { orderId }) => {
      try {
        const order = await Order.findById(orderId)
          .populate('products.productId')
          .populate('shippingAddress');
        return {
          ...order.toObject(),
          id: order._id.toString(),
        };
      } catch (error) {
        throw new Error("Failed to fetch order by ID");
      }
    },
  },

  Mutation: {
    createOrder: async (_, { customerId, products, totalAmount, shippingAddress, paymentMethod }) => {
      try {
        const newOrder = new Order({
          customerId,
          products,
          totalAmount,
          shippingAddress,
          paymentMethod,
        });
        await newOrder.save();

        const merchantIds = [...new Set(products.map(product => product.merchantId.toString()))];
        for (const merchantId of merchantIds) {
          await Merchant.findByIdAndUpdate(merchantId, {
            $push: { orders: newOrder._id }
          });
        }

        return {
          ...newOrder.toObject(),
          id: newOrder._id.toString(),
        };
      } catch (error) {
        throw new Error('Failed to create order');
      }
    },

    updateOrderStatus: async (_, { orderId, status }) => {
      try {
        const order = await Order.findById(orderId);
        if (!order) {
          throw new Error('Order not found');
        }
        order.status = status;
        await order.save();
        return {
          ...order.toObject(),
          id: order._id.toString(),
        };
      } catch (error) {
        throw new Error('Failed to update order status');
      }
    },

    updateOrderStatusByMerchant: async (_, { orderId, status }) => {
      try {
        const updatedOrder = await Order.findByIdAndUpdate(
          orderId,
          { status },
          { new: true }
        ).populate('products.productId').populate('shippingAddress');
        
        return {
          ...updatedOrder.toObject(),
          id: updatedOrder._id.toString(),
        };
      } catch (error) {
        throw new Error('Failed to update order status');
      }
    }
  }
};

module.exports = OrderResolvers;
